language: go
go:
  - 1.11.x

env:
  - GOARCH=amd64

sudo: true

go_import_path: github.com/amyangfei/go-logster

before_install:
  - sudo apt-get install -y logcheck
  - go get github.com/mattn/goveralls

script:
  - env GL_TRAVIS_CI=on ./test.sh
