language: go
go:
  - 1.11.x
  - 1.12

env:
  - GOARCH=amd64

sudo: true

go_import_path: github.com/amyangfei/go-logster

before_install:
  - sudo apt-get install -y logcheck
  - go get github.com/mattn/goveralls

script:
  - make && env GL_TRAVIS_CI=on env UT_PARSER_PLUGIN_PATH=$(pwd)/build/sample_parser.so UT_OUTPUT_PLUGIN_PATH=$(pwd)/build/stdout_output.so ./test.sh
