language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

env:
  - GOARCH=amd64

sudo: false
go_import_path: github.com/amyangfei/go-logster
before_install:
  - go get github.com/mattn/goveralls
script:
  - wget -O dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  - chmod +x dep
  - ./dep ensure
  - ./test.sh
