language: go
go:
  - 1.11.x

env:
  - GOARCH=amd64

sudo: false

go_import_path: github.com/amyangfei/go-logster

before_install:
  - go get github.com/mattn/goveralls

script:
  - ./test.sh
  - env GO111MODULE=on $GOPATH/bin/goveralls -service=travis-ci
